#!/bin/bash

# SSH Connection Script for Ubuntu EC2 Instance
# Auto-generated by Terraform for environment: prod

echo "==============================="
echo "Connecting to Ubuntu EC2 Instance [prod]"
echo "==============================="
echo

PUBLIC_IP="54.198.121.242"
KEY_FILE="./id_rsa_prod"
ENV="prod"

echo "🌍 Environment : $ENV"
echo "🔗 Connecting to: ubuntu@$PUBLIC_IP"
echo "🔑 Using private key: $KEY_FILE"
echo

# Check if private key exists
if [ ! -f "$KEY_FILE" ]; then
    echo "❌ Private key file '$KEY_FILE' not found"
    echo "   Make sure you're running this from the Terraform directory"
    return 1 2>/dev/null || true
fi

# Check private key permissions
KEY_PERMS=$(stat -c "%a" "$KEY_FILE" 2>/dev/null || stat -f "%OLp" "$KEY_FILE" 2>/dev/null)
if [ "$KEY_PERMS" != "400" ]; then
    echo "🔧 Fixing private key permissions..."
    chmod 400 "$KEY_FILE"
fi

# SSH connection
ssh -i "$KEY_FILE" \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=60 \
    ubuntu@$PUBLIC_IP

# Check if SSH failed
if [ $? -ne 0 ]; then
    echo
    echo "❌ SSH connection failed"
    echo "   The instance might still be starting up"
    echo "   Wait a minute and try again"
fi