#!/bin/bash

# SSH Connection Script for Ubuntu EC2 Instance
# Auto-generated by Terraform

echo "==============================="
echo "Connecting to Ubuntu EC2 Instance"
echo "==============================="
echo

PUBLIC_IP="${public_ip}"

echo "🔗 Connecting to: ubuntu@$PUBLIC_IP"
echo "🔑 Using private key: id_rsa"
echo

# Check if private key exists
if [ ! -f "id_rsa" ]; then
    echo "❌ Private key file 'id_rsa' not found"
    echo "   Make sure you're running this from the Terraform directory"
    return 1 2>/dev/null || true
fi

# Check private key permissions
KEY_PERMS=$(stat -c "%a" id_rsa 2>/dev/null || stat -f "%OLp" id_rsa 2>/dev/null)
if [ "$KEY_PERMS" != "400" ]; then
    echo "🔧 Fixing private key permissions..."
    chmod 400 id_rsa
fi

# SSH connection
ssh -i id_rsa \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ConnectTimeout=10 \
    -o ServerAliveInterval=60 \
    ubuntu@$PUBLIC_IP

# Check if SSH failed
if [ $? -ne 0 ]; then
    echo
    echo "❌ SSH connection failed"
    echo "   The instance might still be starting up"
    echo "   Wait a minute and try again"
fi